### ISSUE TITLE
Inside spaces render incorrectly

### ISSUE THREAD

**Issue by ecations** [EternalTrail/eeVR#15]
**Describe the bug**
If the camera is inside an object, the resulting image seems to be incorrect. Instead of stitching together all different sides of the object, the front side seems to be duplicated in all four directions. If the object has holes, the landascape shown through the holes does seem to be correct (not a duplicate of just one direction).

**To Reproduce**
Create a cube. Put the camera inside it. Cut some holes to the cube and make some differences to the four sides of it so that you can recognize which side is which. Render with eeVR. The resulting images will show only one side of the cube.

**Expected behavior**
I'm expecting the render to show all four walls of the object I'm inside, not just one wall duplicated.

**Screenshots**
![problem](https://user-images.githubusercontent.com/51368173/93060743-35aa8780-f67b-11ea-86ad-0e57a045c878.jpg)

**System information (please complete the following information):**
 - OS: Windows 10
 - Processor: Many different tried
 - Graphics card:  RTX2080
 - Graphics driver: 
 - Blender version: 2.9

**Comment by EternalTrail** [comment]
Hello, would you be able to attach the *.blend* file you used for this? It would help in debugging greatly.

**Comment by ecations** [comment]
Hi! Sure, I'll attach the test scene I used here:

https://drive.google.com/file/d/1RZs6dgRy68R3wpKWv-UrXw8ZMNO1QlII/view?usp=sharing

**Comment by EternalTrail** [comment]
It's exactly as I thought! You have the camera as the parent of the box, which makes it rotate together with the camera, as the script makes rotations internally to render the cubemap. Clearing the parent for the box and just adding a copy location constraint to align the box with the camera results with the following image: 
![Render Result 2020-09-14-15-23-48](https://user-images.githubusercontent.com/35872904/93098263-93040000-f69e-11ea-80ce-5160cdf86e8c.png)
A temporary solution to your issue is to not make the camera a parent of any objects, I might solve this in the future by just spawning a separate camera into the scene purely for rendering the cubemap.

**Comment by ecations** [comment]
Thanks for looking into this! Good ideas for the future! In the meanwhile it might be helpful to mention that the camera should not have any children in the documentation (at the moment it gives the impression that the camera should not have any parents). Thanks again!
