### ISSUE TITLE
Can't install right from them git or ZIP

### ISSUE THREAD

**Issue by illuusio** [EternalTrail/eeVR#22]
**Describe the bug**
This is kind of TL;DR problem (didn't even try read first sentences from REAME.md).
I just grabbed ZIP and tries to install it under Blender 2.91 addons and assumed that everything would be ok.
But as expected nothings showed up.
After that I little bit reorganized VRRenderer.py register- and unregister-method to new and shiny __init__.py and after that I was happy camper as it showed up on addons/testing and worked as expected

**To Reproduce**
1. Go to GIT repo down load master ZIP
2. Try to install with install from Blender
3. Nothing happens (there is no such addon)

**Expected behavior**
Downloading and installing ZIP or pulling git down to addons dir should work out-of-the box

**System information (please complete the following information):**
 - OS: Linux
 - Blender version: 2.91

**Additional context**
Just asking is this something that is wanted as PR as I did the needed changes?

**Comment by EternalTrail** [comment]
Sorry for the very late response. This is definitely an issue that a lot of people run into and it definitely needs changing. Can you [email me](mailto:andriux19960823@gmail.com) the changes you've made, so that I could implement them? (Or you could implement the changes yourself on the latest version of the program and create a pull request, either way credit goes to you for making the changes!)

**Comment by illuusio** [comment]
No problem.. I'll create PR
