### ISSUE TITLE
eeVR dont render volumetrics

### ISSUE THREAD

**Issue by lenonfx** [EternalTrail/eeVR#33]
I've been trying to render a 360 with Pure Sky to use enviroment in a 3D scene but in the eeVR render the volumetrics don't show up.

**Comment by EternalTrail** [comment]
Might be something related to how blender internally renders the images, since eeVR internally just calls  bpy.ops.render.render(write_still=True) which renders a still image and the stitching is done afterwards, I'm unclear on how Pure Sky works but it could be that Pure Sky doesn't work with addons that rely on this function. I'd need to look into how Pure Sky works before I make a fix.

**Comment by SAM-tak** [comment]
Unable to reproduce.
