### ISSUE TITLE
Complex volumetrics make visible seams

### ISSUE THREAD

**Issue by elpathooo** [EternalTrail/eeVR#35]
Hello,
I have the camera inside cube with volumetric shader. When I use plain even distributed volume then everything is ok, but when I use cloud texture on it, every picture has different level of transparency. Final image is stitched from vastly different images. It looks like the different angle makes the volume look different.

Thank you for your help.

**Comment by EternalTrail** [comment]
If the how the volumetric looks is angle dependent, any solution involving cubemap projection (which is what eeVR is based on) is out of the question. My advice is to see if you can get your volumetrics to not be dependent angle. This could also be due to screen-space lighting effects that cause the volumetric to appear different. In general, these types of issues are probably best to be avoided. I'll leave this issue open just a reminder to add a bit of documentation what will work and what won't with this addon. If you think the issue you're having is not due to what I've explained above please feel free to give me more information, such as a blend file and/or some images that would help me understand the issue, also more information on what kinds of addons you're using and your blender version would help as well.

**Comment by SAM-tak** [comment]
Already fixed.
maybe.
