### ISSUE TITLE
New camera Created each time i hit render, meaning no keyframe animation for the camera possible? 

### ISSUE THREAD

**Issue by HardcoreRick** [EternalTrail/eeVR#41]
When trying to render the animation it seems to create anew camera each time, meaning that I can't render from an existing 360 camera that I have added animation to. Am i right in thinking its impossible to do a moving camera render?

**Comment by HardcoreRick** [comment]
OK the project is due tomorrow - But it works!! I can't believe it haha
I may have to re render every frame because now I get lovely bloom etc -
plug in is great :)

I don't know if this was necessary but I re-saved the project in a new
directory, sometimes came out in a strange square format, like when you
have the grid of 9 but saved as separate files, maybe that's just how the
plug in works it out? Its really interesting.

But my apologies, it works great! Even with animation :)

Thanks for getting me to give it another go!

Jasper

**Comment by HardcoreRick** [comment]
I've just had something else come up - it doesn't seem to like bloom very
much?

[image: image.png]

**Comment by EternalTrail** [comment]
Yes, bloom is a post-process effect. Similar to screen-space reflections and other similar effects it will create visible seams. Turning on overscan could mitigate the issue to some extent but it won't remove it. That's the main disadvantage of this program currently, I will hopefully solve it some time in the future. For now I'm closing this since the original issue seems to have been answered. If you have any further questions you're free to email me or post a new issue (more likely to reply in a reasonable amount of time on my email).

**Comment by HardcoreRick** [comment]
Thanks for getting back to me!

Using Evee for VR is such a great resource so I'm glad you are still
working on this.

I have just finished rendering my current project in cycles - it was
horrific!  - but ill try and replicate the issue and send over a report
soon.

Thanks again - J
