### ISSUE TITLE
Allow choosing output location for intermediate images

### ISSUE THREAD

**Issue by shankarsivarajan** [EternalTrail/eeVR#58]
**Describe the bug**
Blender needs to be run as administrator. If run normally, the addon produces the error
`RuntimeError: Error: Render error (Invalid argument) cannot save: 'C:\temp_img_store_28300_top.png'`

The addon is trying to save images to a location Blender doesn't have permission to access, namely `C:\`. If Blender is run as administrator, it works correctly, with the final image written to the location I set in the `Output` panel. The problem is that I can't choose where the intermediate images, the ones with suffix `_top`, `_right`, etc., get saved.

**To Reproduce**
1. Install and enable `eeVR` addon.
2. Open a new Blender file and save.
3. Set render engine to Eevee.
4. `Render Image` in eeVR panel.
5. See error in console.

**Expected behavior**
Image saved correctly.

**System information (please complete the following information):**
 - OS: Windows 10
 - Blender version: 4.0.2

**Comment by SAM-tak** [comment]
@shankarsivarajan

Please change the path set in the Temporary Files of Preferences.

eeVR creates temporary files in the location specified here, so it is necessary to have a valid path with write permissions set.

If administrator privileges are required directly under the C drive, it is advisable to specify a location where you can write access with user privileges. Otherwise, not only eeVR but also other add-ons may have operational problems. 

![image](https://github.com/EternalTrail/eeVR/assets/250165/67176553-f501-4f26-982b-156e758ab927)

**Comment by shankarsivarajan** [comment]
Thanks! That path was blank, and setting it fixed it.
